<%@ Page Title="" Language="C#" MasterPageFile="~/Main.Master" AutoEventWireup="true" CodeBehind="UserGrid.aspx.cs" Inherits="Online_Real_Estate.UserGrid" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
        <div>
            <table>
                <tr>
                    <td>
                        <asp:GridView ID="userGrid" runat="server" DataKeyNames="UserID" AutoGenerateColumns="False" AutoGenerateDeleteButton ="True" AutoGenerateEditButton="true" OnRowDeleting="userGrid_RowDeleting" OnRowEditing="userGrid_RowEditing" OnRowCancelingEdit="userGrid_RowCancelingEdit">
                            <Columns>
                                <asp:TemplateField HeaderText="Name">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="nameId" runat="server" Text='<%# Bind("UserName") %>'>
                                            </asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="nameLabel" runat="server" Text='<%# Bind("UserName") %>'>



                                            </asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                   <asp:TemplateField HeaderText="UserId">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="userId" runat="server" Text='<%# Bind("UserId") %>'>
                                            </asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="userLabel" runat="server" Text='<%# Bind("UserId") %>'>
                                            </asp:Label>
                                    </ItemTemplate>
                                       </asp:TemplateField>
                                  <asp:TemplateField HeaderText="Password">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="passwordId" runat="server" Text='<%# Bind("Password") %>'>
                                            </asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="passwordLabel" runat="server" Text='<%# Bind("Password") %>'>
                                            </asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Mail_ID">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="mailId" runat="server" Text='<%# Bind("Mail_ID") %>'>
                                            </asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="mailLabel" runat="server" Text='<%# Bind("Mail_ID") %>'>
                                            </asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                              
                                        <asp:TemplateField HeaderText="Location">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="locationId" runat="server" Text='<%# Bind("Location") %>'>
                                            </asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="locationLabel" runat="server" Text='<%# Bind("Location") %>'>
                                            </asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="PhoneNumber">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="phoneId" runat="server" Text='<%# Bind("Phone_Number") %>'>
                                            </asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="phoneLabel" runat="server" Text='<%# Bind("Phone_Number") %>'>
                                            </asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Role">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="roleId" runat="server" Text='<%# Bind("Role") %>'>
                                            </asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="roleLabel" runat="server" Text='<%# Bind("Role") %>'>
                                            </asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                 </Columns>
                        </asp:GridView>
                    </td>
                </tr>
            </table>
        </div>
</asp:Content>
